#!/bin/bash

#**************************************************************
# Get the versions
#**************************************************************
. ./version

#**************************************************************
# Deploy 'players-api' to 'staging'
#**************************************************************
GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

REPOSITORY_URL="https://server.rsmaxwell.co.uk/archiva/repository"
REPOSITORYID="staging"
REPOSITORY="staging"
GROUPID="com.rsmaxwell.players"
NAME="players-api"
VERSION=${players_api_version}
PACKAGING="zip"

URL=${REPOSITORY_URL}/${REPOSITORY}/
ARTIFACTID=${NAME}-${GOARCH}-${GOOS}


filename=${ARTIFACTID}-${VERSION}.${PACKAGING}
pathname=${HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${filename}


if [ ! -f ${pathname} ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

cp ${pathname} .
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

CLASSIFIER_TEST="test"
FILENAME_TEST=${ARTIFACTID}-${VERSION}-${CLASSIFIER_TEST}.${PACKAGING}
pathname_test=${HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${FILENAME_TEST}

if [ ! -f ${pathname_test} ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

cp ${pathname_test} .
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mvn --batch-mode deploy:deploy-file \
	-Durl=${URL}  \
	-DrepositoryId=${REPOSITORYID} \
	-Dfile=${FILENAME} \
	-DgroupId=${GROUPID} \
	-DartifactId=${ARTIFACTID} \
	-Dversion=${VERSION} \
	-Dpackaging=${PACKAGING} \
	-Dfiles=${FILENAME_TEST} \
	-Dclassifiers=${CLASSIFIER_TEST} \
	-Dtypes=zip \
	1>stdout.txt 2>stderr.txt
	
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "----[ stdout ]--------------------------"
    cat stdout.txt
    echo "----[ stderr ]--------------------------"
    cat stderr.txt
    echo "----------------------------------------"
    exit 1
fi