#!/bin/bash

#**************************************************************
# Get the versions
#**************************************************************
. ./version

#**************************************************************
# Deploy 'players-api' to 'internal'
#**************************************************************
GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

REPOSITORY_URL="https://server.rsmaxwell.co.uk/archiva/repository"
REPOSITORYID="internal"
REPOSITORY="internal"
GROUPID="com.rsmaxwell.players"
NAME="players-api"
VERSION=${players_api_version}
PACKAGING="zip"

ARTIFACTID=${NAME}-${GOARCH}-${GOOS}
URL=${REPOSITORY_URL}/${REPOSITORY}/

filename=${ARTIFACTID}-${VERSION}.${PACKAGING}
pathname=${HOME}/.m2/repository/${GROUPID//.//}/${ARTIFACTID}/${VERSION}/${filename}
if [ ! -f ${pathname} ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

cp ${pathname} .
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mvn --batch-mode deploy:deploy-file \
	-DgroupId=${GROUPID} \
	-DartifactId=${ARTIFACTID} \
	-Dversion=${VERSION} \
	-Dpackaging=${PACKAGING} \
	-Dfile=${filename} \
	-DrepositoryId=${REPOSITORYID} \
	-Durl=${URL}  1>stdout.txt 2>stderr.txt
	
result=$?
if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "----[ stdout ]--------------------------"
    cat stdout.txt
    echo "----[ stderr ]--------------------------"
    cat stderr.txt
    echo "----------------------------------------"
    exit 1
fi