#!/bin/bash

rc=0

generate_test_data=$(find $(pwd)/build -name generate-test-data*)
players_api=$(find $(pwd)/build -name players-api*)

cd build
jq . version.json

export PORT=4202
export PLAYERS_API_ROOTDIR="database"

${generate_test_data}
${players_api} &
PID=$!

echo "... sleeping 10 seconds ..."
sleep 10

echo "killing the 'players-api' process"
kill ${PID}

exit ${rc}
