#!/bin/bash

#**************************************************************
# Get the version
#**************************************************************
cd build
pwd
ls -al 
jq . version.json

generate-test-data=$(find . -name generate-test-data*)
players-api=$(find . -name players-api*)

export PORT=4202
export PLAYERS_API_ROOTDIR="database"

./${generate-test-data}
./${players-api} &
PID=$!

echo "... sleeping 10 seconds ..."
sleep 10

echo "killing the 'players-api' process"
kill $FOO_PID
